from .help import CogHelp
from .passation import CogPassation
from .infoFromIP import CogIpInfo
from .invitation import CogInvitation
from .newyear import CogNewyear
from .NSandSOALookup import CogLookup
from .videoDiplomes import CogVideoDiplomes
from .international import CogInternational
from .vendrediChill import CogVendrediChill
from .calendar import CogCalendar
from .tgg import CogTGG
from .bastos import CogBastosTwitch
from .pot_tres_confine import CogPotTresConfine
