name : build & push to registry (bot discord image)

on :
  push :
    branches :
      - master

env :
  IMAGE_NAME : ${{ secrets.URL_REGISTRY }}/astusbot

jobs :
  buildandpush:
    runs-on : ubuntu-latest
    steps :
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1


      - name: Build image with Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
            --output "type=image,push=true" \
            --tag $IMAGE_NAME \
            --file Dockerfile ./